<a href="https://colab.research.google.com/github/wannasmile/colab_code_note/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **打印数组**

In [1]:
import numpy as np
a = np.arange(6) # 1d array
print(a)
b = np.arange(12).reshape(4,3) # 2d array
print(b)
c = np.arange(24).reshape(2,3,4) # 3d array
print(c)

print(np.arange(10000))
print(np.arange(10000).reshape(100,100))

#np.set_printoptions(threshold=sys.maxsize)

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


当打印数组时，NumPy以与嵌套列表类似的方式显示它，通过以下布局显示：

(d1,d2,...,dm,dn)

> 最后一个轴(dn)从左到右打印；倒数第二个(dm)从上到下打印；其余部分也从上到下打印，每个切片用空行分隔。

> 如果数组太大而无法打印，NumPy会自动跳过数组的中心部分并仅打印角点。

> 要禁用此行为并强制NumPy打印整个数组，可以更改打印选项set_printoptions（np.set_printoptions(threshold=sys.maxsize)）。




# **数学运算**

In [2]:
import numpy as np
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print( b )
c = a-b
print( c )
print( b**2 )
print( 10*np.sin(a) )
print( a<35 )


A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )

print( A * B ) # elementwise product

print( A @ B ) # matrix product

print( A.dot(B) ) # another matrix product



a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
b += a

#UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
#b is not automatically converted to integer type
#a += b 


a = np.random.random((2,3))
print( a )
print(a.sum())
print(a.min())
print(a.max())



b = np.arange(12).reshape(3,4)
print( b )
print( b.sum(axis=0) ) #shape=(3,4) from left to right: axis 0 # sum of each axis, along axis 0
print( b.min(axis=1) ) #shape=(3,4) from left to right: axis 1 # min of each axis, along axis 1
print( b.cumsum(axis=1) ) #cumulative sum along axis 1

[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
[[0.49634124 0.63803686 0.98850305]
 [0.22713425 0.21708148 0.44409985]]
3.0111967340552397
0.217081482049437
0.9885030491343514
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


数组上的算术运算符会应用到 元素 级别。

与许多矩阵语言不同，乘积运算符*在NumPy数组中按元素进行运算。矩阵乘积可以使用@运算符（在python>=3.5中）或dot函数或方法执行。

某些操作（例如+=和*=）会更直接更改被操作的矩阵数组而不会创建新矩阵数组。

当使用不同类型的数组进行操作时，结果数组的元素类型为更一般类型的数组（称为向上类型转换的行为）。

许多一元操作，例如计算数组中所有元素的总和，都是作为ndarray类的方法实现的。
默认情况下，这些一元操作适用于整个数组，就像它是一个数字列表一样，无论其形状如何。但是，通过指定axis参数，就可以沿数组的指定轴应用操作。

# **通用函数**

In [3]:
B = np.arange(3)
print( np.exp(B) )
print( np.sqrt(B) )
C = np.array([2., -1., 4.])
print( np.add(B, C) )


print("\n\nall:\n")

print( np.all([[True,False],[True,True]]) )
print( np.all([[True,False],[True,True]], axis=0) )
print( np.all([1.0, np.nan]) )


print("\n\napply_along_axis:\n")

def my_func(a):
  """Average first and last element of a 1-D array"""
  return (a[0] + a[-1]) * 0.5
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print( np.apply_along_axis(my_func, 0, b) )
print( np.apply_along_axis(my_func, 1, b) )



b = np.array([[8,1,7], [4,3,9], [5,2,6]])
print( np.apply_along_axis(sorted, 1, b) )



b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print( np.apply_along_axis(np.diag, -1, b) )


print("\n\nargmax:\n")

a = np.arange(6).reshape(2,3) + 10
print( a )
print( np.argmax(a) )
print( np.argmax(a, axis=0) )
print( np.argmax(a, axis=1) )



print("\n\nargsort:\n")

x = np.array([3, 1, 2])
print( np.argsort(x) )


x = np.array([[0, 3], [2, 2]])
print( x )

ind = np.argsort(x, axis=0)
print( ind )
print( np.take_along_axis(x, ind, axis=0) )



print("\n\nwhere:\n")

a = np.arange(10)
print( a )

print( np.where(a < 5, a, 10*a) )



print(
np.where([[True, False], [True, True]],
         [[1, 2], [3, 4]],
         [[9, 8], [7, 6]])
)
a = np.array([[0, 1, 2],
              [0, 2, 4],
              [0, 3, 6]])
print( np.where(a < 4, a, -1) ) #-1 is broadcast




print("\n\nvectorize:\n")

def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a > b:
        return a - b
    else:
        return a + b


vfunc = np.vectorize(myfunc)

print(
vfunc([1, 2, 3, 4], 2)
)




def mypolyval(p, x):
    _p = list(p)
    res = _p.pop(0)
    while _p:
        res = res*x + _p.pop(0)
    return res

vpolyval = np.vectorize(mypolyval, excluded=['p'])

print(
vpolyval(p=[1, 2, 3], x=[0, 1])
)

vpolyval.excluded.add(0)
print(
vpolyval(p=[1, 2, 3], x=[0, 1])
)



print(np.eye(4))
convolve = np.vectorize(np.convolve, signature='(n),(m)->(k)')
print( convolve(np.eye(4), [1, 2, 1]) )

print( convolve(np.ones((2,2)), [1, 2, 1]) )
#bincount
#Count number of occurrences of each value in array of non-negative ints.



#ceil
#Return the ceiling of the input, element-wise.

#floor
#Return the floor of the input, element-wise.

#clip
#Clip (limit) the values in an array.


#cross
#Return the cross product of two (arrays of) vectors.

#dot
#Dot product of two arrays.



#var
#Compute the variance along the specified axis.

#std
#Compute the standard deviation along the specified axis.

#conj
#Return the complex conjugate, element-wise.

#corrcoef
#Return Pearson product-moment correlation coefficients.

#cov
#Estimate a covariance matrix, given data and weights.

#trace
#Return the sum along diagonals of the array.

#transpose
#Reverse or permute the axes of an array; returns the modified array.



[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 6.]


all:

False
[ True False]
True


apply_along_axis:

[4. 5. 6.]
[2. 5. 8.]
[[1 7 8]
 [3 4 9]
 [2 5 6]]
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]

 [[7 0 0]
  [0 8 0]
  [0 0 9]]]


argmax:

[[10 11 12]
 [13 14 15]]
5
[1 1 1]
[2 2]


argsort:

[1 2 0]
[[0 3]
 [2 2]]
[[0 1]
 [1 0]]
[[0 2]
 [2 3]]


where:

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 50 60 70 80 90]
[[1 8]
 [3 4]]
[[ 0  1  2]
 [ 0  2 -1]
 [ 0  3 -1]]


vectorize:

[3 4 1 2]
[3 6]
[3 6]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 2. 1. 0. 0. 0.]
 [0. 1. 2. 1. 0. 0.]
 [0. 0. 1. 2. 1. 0.]
 [0. 0. 0. 1. 2. 1.]]
[[1. 3. 3. 1.]
 [1. 3. 3. 1.]]


NumPy提供熟悉的数学函数，例如sin，cos和exp。

在NumPy中，这些被称为“通用函数”（ufunc）。

在NumPy中，这些函数在数组上按元素进行运算，产生一个数组作为输出。

其他通用函数：all， any， apply_along_axis， argmax， argmin， argsort， average， bincount， ceil， clip， conj， corrcoef， cov， cross， cumprod， cumsum， diff， dot， floor， inner， lexsort， max， maximum， mean， median， min， minimum， nonzero， outer， prod， re， round， sort， std， sum， trace， transpose， var， vdot， vectorize， where。（ https://numpy.org/devdocs/reference/ufuncs.html ）