<a href="https://colab.research.google.com/github/wannasmile/colab_code_note/blob/main/PYT002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# https://pytorch.org/tutorials/beginner/colab
%matplotlib inline



张量
=======

张量是一种专门的数据结构，它们与数组和矩阵非常相似。在PyTorch中，我们使用张量来编码模型的输入和输出，以及模型的参数。

张量类似于NumPy的ndarrays，只不过张量可以在GPU或其他硬件加速器上运行。事实上，张量和NumPy数组往往可以共享同一段底层内存，这样就无需复制数据。张量还针对自动求微分进行了优化（我们将在后面的Autograd部分进一步了解这一点）。如果你已经熟悉ndarrays，那么使用Tensor API就会感觉很自在。如果不熟悉，也可以跟着继续学习！


In [ ]:
import torch
import numpy as np

初始化张量
=====================


张量可以通过多种方式初始化。以下是一些示例：


**直接从数据初始化**

张量可以直接从数据创建。数据类型会自动推断。


In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

**从NumPy数组**

张量可以从NumPy数组创建（反之亦然）。


In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**从另一个张量**

新张量保留了参数张量的属性（形状、数据类型），除非显式覆盖。

In [ ]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6681, 0.6524],
        [0.1420, 0.6029]]) 



**使用随机值或常量值**

shape是一个张量维度的元组。在下面的函数中，它决定了输出张量的维度。


In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8797, 0.4959, 0.1810],
        [0.9698, 0.3987, 0.6632]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


------------------------------------------------------------------------


张量的属性
======================

张量的属性描述了它们的形状、数据类型以及它们所存储的设备。


In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


------------------------------------------------------------------------


张量上的操作
=====================

包括算术、线性代数、矩阵操作（转置、索引、切片）、采样等等在内的100多个张量操作在此处有详细描述。

这些操作都可以在GPU上运行（通常比在CPU上运行速度更快）。如果您使用的是Colab，可以通过前往“运行时”>“更改运行时类型”>“GPU”来分配GPU。

默认情况下，张量是在CPU上创建的。我们需要使用.to方法显式地将张量移动到GPU上（在检查GPU可用性之后）。请注意，在不同设备之间复制大张量在时间和内存方面可能代价很大！

In [ ]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

尝试从列表中执行一些操作。如果您已经熟悉NumPy API，您会发现Tensor API非常易于使用。

**标准的类似NumPy的索引和切片**


In [ ]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**连接张量**

您可以使用torch.cat来沿着给定的维度连接一系列张量。另请参阅torch.stack，这是另一种略有不同的张量连接操作。

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t2)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**算术操作**


In [ ]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

这段代码展示了在PyTorch中对张量（tensor）进行矩阵乘法（也称为矩阵乘积）和逐元素乘法（也称为逐元素积）的几种不同方法。我们将逐一解释每个部分。

### 矩阵乘法

1. **使用`@`运算符**
   ```python
   y1 = tensor @ tensor.T
   ```
   这里使用了`@`运算符来进行矩阵乘法。`tensor.T`表示`tensor`的转置。结果是`y1`成为`tensor`和它的转置的矩阵乘积。

2. **使用`matmul`方法**
   ```python
   y2 = tensor.matmul(tensor.T)
   ```
   这也是进行矩阵乘法，`matmul`方法直接作用于`tensor`对象上，同样需要对其中一个张量进行转置以确保乘法操作的正确执行。

3. **使用`matmul`函数并指定输出张量**
   ```python
   y3 = torch.rand_like(y1)
   torch.matmul(tensor, tensor.T, out=y3)
   ```
   这行代码首先创建了一个与`y1`形状和数据类型相同的随机张量`y3`，然后通过`torch.matmul`函数进行矩阵乘法，并将结果存储在`y3`中。这里`out=y3`参数指定了输出张量。

### 逐元素乘法

1. **使用`*`运算符**
   ```python
   z1 = tensor * tensor
   ```
   `*`运算符用于逐元素乘法，即将`tensor`中的每个元素自乘，结果赋值给`z1`。

2. **使用`mul`方法**
   ```python
   z2 = tensor.mul(tensor)
   ```
   同样，`mul`方法也是用来执行逐元素乘法，这里的`tensor`对象调用了`mul`方法对自身进行乘法操作。

3. **使用`mul`函数并指定输出张量**
   ```python
   z3 = torch.rand_like(tensor)
   torch.mul(tensor, tensor, out=z3)
   ```
   这里首先创建了一个与`tensor`具有相同形状和数据类型的随机张量`z3`，然后使用`torch.mul`函数执行逐元素乘法，并将结果存储在`z3`中。

通过这些示例，可以看出PyTorch提供了多种方法来进行相同的操作，包括使用运算符、方法或函数，并且还支持直接在一个预先分配好的张量中存储结果，这样做可以在进行大规模操作时节省内存和时间。

**单元素张量**

如果您有一个单元素的张量，例如，通过将所有张量值汇总为一个值，您可以使用item()方法将其转换为Python数值。


In [ ]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


**就地操作**


将结果存储在操作数中的操作称为就地操作。它们通过下划线后缀来表示。例如：x.copy_(y)，x.t_()，将会改变x。


In [ ]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>注意：</strong></div>
<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">
<p>就地操作可以节省一些内存，但在计算导数时会因为立即失去历史记录而变得问题重重。因此，不鼓励使用就地操作。</p>
</div>





------------------------------------------------------------------------


与NumPy的桥接
=================

CPU上的张量和NumPy数组可以共享它们的基础内存位置，改变其中一个也将改变另一个。

张量转NumPy数组
=====================


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


张量的更改会反映在NumPy数组中。

In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy数组转张量
=====================


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

NumPy数组的更改会反映在张量中。

In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
