<a href="https://colab.research.google.com/github/wannasmile/colab_code_note/blob/main/Pytorch001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
import numpy as np

torch 基本处理单元

In [3]:
# 返回的数组大小5x4的矩阵
torch.Tensor(5, 4)

tensor([[7.3237e+07, 4.3977e-41, 7.3237e+07, 4.3977e-41],
        [5.8260e+00, 4.3977e-41, 5.8263e+00, 4.3977e-41],
        [1.1848e+07, 4.3977e-41, 5.8605e+00, 4.3977e-41],
        [5.8606e+00, 4.3977e-41, 5.8606e+00, 4.3977e-41],
        [5.8607e+00, 4.3977e-41, 5.8607e+00, 4.3977e-41]])

In [4]:
# 返回的数组大小是5x4的矩阵，初始化是0~1的均匀分布
torch.rand(5, 4)

tensor([[0.8667, 0.6007, 0.9300, 0.7184],
        [0.0227, 0.6722, 0.8642, 0.3673],
        [0.5254, 0.6339, 0.7068, 0.5538],
        [0.2375, 0.2451, 0.0163, 0.1413],
        [0.0806, 0.2418, 0.0918, 0.2829]])

In [5]:
# 得到矩阵大小
a = torch.rand(5, 4)
a.size()

torch.Size([5, 4])

In [6]:
# numpy 类似的返回5x4大小的矩阵
np.ones((5, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# numpy 和 torch.Tensor 之间的转换
a = torch.rand(5, 4)
b = a.numpy()
print(b)

[[0.79515415 0.02142662 0.59408677 0.4819622 ]
 [0.08151072 0.17280215 0.5513895  0.29636782]
 [0.29597902 0.48499048 0.32279682 0.5102671 ]
 [0.84397537 0.1622588  0.34312546 0.2514106 ]
 [0.89354765 0.8457858  0.2619503  0.17854983]]


In [8]:
a = np.array([[3, 4], [3, 6]])
b = torch.from_numpy(a)
print(b)

tensor([[3, 4],
        [3, 6]])


运算和 numpy 类似

In [9]:
x = torch.rand(5, 4)
y = torch.rand(5, 4)
c = 3

In [10]:
print(c * x)

tensor([[1.2428, 2.5549, 0.6651, 0.5002],
        [1.5732, 2.6009, 2.9278, 2.9123],
        [0.3466, 1.2155, 0.8275, 2.3473],
        [0.7705, 1.8962, 1.2504, 0.1158],
        [2.4050, 2.1692, 1.6353, 0.1055]])


In [11]:
print(x + y)

tensor([[0.6458, 1.5138, 0.7612, 0.4023],
        [1.3130, 1.6622, 1.5202, 1.8372],
        [0.6705, 0.9567, 1.0255, 1.5648],
        [0.5335, 1.0516, 1.1102, 0.8963],
        [1.5744, 1.6618, 1.3948, 0.4319]])


In [12]:
print(x.add(y))

tensor([[0.6458, 1.5138, 0.7612, 0.4023],
        [1.3130, 1.6622, 1.5202, 1.8372],
        [0.6705, 0.9567, 1.0255, 1.5648],
        [0.5335, 1.0516, 1.1102, 0.8963],
        [1.5744, 1.6618, 1.3948, 0.4319]])


In [13]:
# 可以直接进行操作改变原对象，x+y或者x.add()并不会改变x，但是x.add_()则会对x进行改变
x.add_(y)

tensor([[0.6458, 1.5138, 0.7612, 0.4023],
        [1.3130, 1.6622, 1.5202, 1.8372],
        [0.6705, 0.9567, 1.0255, 1.5648],
        [0.5335, 1.0516, 1.1102, 0.8963],
        [1.5744, 1.6618, 1.3948, 0.4319]])

In [14]:
print(x)

tensor([[0.6458, 1.5138, 0.7612, 0.4023],
        [1.3130, 1.6622, 1.5202, 1.8372],
        [0.6705, 0.9567, 1.0255, 1.5648],
        [0.5335, 1.0516, 1.1102, 0.8963],
        [1.5744, 1.6618, 1.3948, 0.4319]])


将 torch.Tensor 放到 GPU 上

In [15]:
# 判断一下电脑是否支持GPU
torch.cuda.is_available()

False

In [16]:
a = torch.rand(5, 4)
#a = a.cuda()
print(a)

tensor([[0.2101, 0.9985, 0.4116, 0.0330],
        [0.6829, 0.0740, 0.0880, 0.4537],
        [0.1606, 0.9148, 0.2012, 0.0273],
        [0.6791, 0.4662, 0.5712, 0.1808],
        [0.1056, 0.1685, 0.7522, 0.9632]])


torch 的自动求导功能

torch 和大部分框架一样有着自动求导功能，对象不再是 torch.Tensor，而是 torch.autograd.Variable

本质上 Variable 和 Tensor 没有什么区别，不过 Variable 会放在一个计算图里面，可以进行前向传播和反向传播以及求导

autograd.Variable = data + grad + creator

里面的 creator 表示通过什么操作得到的这个 Variable，grad 表示反向传播的梯度

In [17]:
from torch.autograd import Variable

In [18]:
# requires_grad 表示是否对其求梯度，默认是 False
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([5]), requires_grad=True)
z = 2 * x + y + 4

In [19]:
# 对 x 和 y 分别求导
z.backward()

In [20]:
# x 的导数和 y 的导数
print('dz/dx: {}'.format(x.grad.data))
print('dz/dy: {}'.format(y.grad.data))

dz/dx: tensor([2.])
dz/dy: tensor([1.])


神经网络部分
所依赖的主要是 torch.nn 和 torch.nn.functional

torch.nn 里面有着所有的神经网络的层的操作，其用来构建网络，只有执行一次网络的运算才执行一次

torch.nn.functional 表示的是直接对其做一次向前运算操作


In [21]:
from torch import nn
import torch.nn.functional as F

In [22]:
# 基本的网络构建类模板
class net_name(nn.Module):
    def __init__(self):
        super(net_name, self).__init__()
        # 可以添加各种网络层
        self.convl = nn.Conv2d(3, 10, 3)
        # 具体每种层的参数可以去查看文档

    def forward(self, x):
        # 定义向前传播
        out = self.convl(x)
        return out