<a href="https://colab.research.google.com/github/wannasmile/colab_code_note/blob/main/SMALL001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Small Is the New Big

带权重做聚类

In [ ]:
from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import pairwise_distances_argmin
from sklearn.metrics.pairwise import pairwise_distances
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 假设有以下特征数据
X = np.array([[1, 2], [1, 4], [1, 0],
              [10, 2], [10, 4], [10, 0]])

# 定义权重
feature_weights = [10, 1]  # 假设我们更关心第一个特征

# 标准化数据并应用权重
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
X_scaled_weighted = X_scaled * feature_weights

# 使用权重后的数据进行聚类
kmeans = KMeans(n_clusters=3)
kmeans.fit(X_scaled_weighted)

# 获取聚类中心
centroids = kmeans.cluster_centers_

# 反标准化中心点以得到原始特征空间的表示
centroids_scaled = centroids / feature_weights
centroids_original = scaler.inverse_transform(centroids_scaled)

print("Cluster centers (scaled):\n", centroids_scaled)
print("Cluster centers (original):\n", centroids_original)

# 预测
labels = kmeans.predict(X_scaled_weighted)
print("Predicted labels:\n", labels)

Cluster centers (scaled):
 [[0.   0.75]
 [1.   0.5 ]
 [0.   0.  ]]
Cluster centers (original):
 [[ 1.  3.]
 [10.  2.]
 [ 1.  0.]]
Predicted labels:
 [0 0 2 1 1 1]


Git要求每个提交都关联一个用户身份，包括用户名和电子邮件地址。这不仅帮助确认提交的作者，也有助于跟踪谁做了更改。以下是如何设置你的Git用户身份的步骤：

### 1. 设置全局用户身份

如果你希望在所有的项目中使用相同的用户身份，你可以为Git设置全局配置。打开终端或命令提示符，并运行以下命令：

```bash
git config --global user.name "Your Name"
git config --global user.email you@example.com
```

将 `"Your Name"` 替换为你的名字，将 `you@example.com` 替换为你的电子邮件地址。

### 2. 设置本地仓库的用户身份

如果你只在特定的项目或仓库中使用特定的用户身份，你可以为那个仓库设置本地配置。这意味着身份仅在该仓库中有效。在终端或命令提示符中，导航到你的仓库目录，并运行：

```bash
git config user.name "Your Name"
git config user.email you@example.com
```

同样，将 `"Your Name"` 和 `you@example.com` 替换为你的名字和电子邮件地址。**注意**，这次命令中不加 `--global` 参数。

### 3. 验证配置

你可以通过以下命令来验证你的配置已经生效：

```bash
git config --list
```

这个命令会显示你的所有Git配置选项和值，包括用户身份配置。

### 4. 继续你的Git操作

配置完毕后，你可以继续之前尝试进行的Git操作，比如提交更改（commit）。如果之前遇到错误，现在应该能够顺利进行。

### 小贴士

- 确保你的电子邮件地址是有效的，并且在相应的Git平台（如GitHub、GitLab、Bitbucket等）上与你的账户相关联。
- 如果你在多个Git托管服务上工作，可能需要为不同的服务使用不同的电子邮件地址。在这种情况下，为每个仓库设置本地用户身份可能是更好的选择。



当你在Visual Studio Code (VS Code) 中使用Git，遇到“没有暂存的更改来提交”的消息时，这通常意味着在你尝试提交之前，没有对代码或文件进行更改，或者你没有将这些更改暂存。以下是一些步骤和建议，帮助你在遇到这种情况时进行排查和处理：

### 1. 确认更改
首先，请确保你已经对项目中的文件做了更改。可以在VS Code的**源代码管理**面板（左侧导航栏中的第4个图标）或编辑器底部的状态栏上查看是否有未提交的更改。

### 2. 查看文件状态
在VS Code的终端（**Terminal**）中，导航到你的项目目录并运行以下命令来查看文件状态：
```bash
git status
```
这个命令会显示哪些文件有了更改但还未暂存，以及哪些文件还未被跟踪。

### 3. 暂存更改
如果文件已经有了更改但还没有暂存，你需要将它们添加到暂存区。在**源代码管理**面板中，你可以通过点击未暂存文件旁边的`+`号来暂存更改。你也可以在终端中使用以下命令来添加：
```bash
git add .
```
这个命令会将所有更改过的文件添加到暂存区。如果你只想添加特定的文件，可以将`.`替换为文件名。

### 4. 提交更改
确保你已经暂存了需要提交的更改后，就可以在**源代码管理**面板中填写提交信息，然后点击提交按钮（通常是类似对勾的图标）。或者，在终端中执行：
```bash
git commit -m "你的提交信息"
```
替换`"你的提交信息"`为你的具体情况。

### 5. 检查.gitignore文件
如果你的更改没有出现在**未暂存**的列表中，可能是因为这些更改的文件被`.gitignore`文件中的规则所忽略。请检查你的`.gitignore`文件，确保你的更改不会因此被忽略。

### 6. 确认Git分支
有时候，你可能在错误的分支上工作。使用`git branch`命令检查当前所在的分支，确保你在正确的分支上提交更改。

### 7. 同步远程更改
如果其他人在同一个项目上工作并且已经推送了更改，你可能需要先拉取这些更改再提交：
```bash
git pull
```
这会获取远程分支的最新更改并与你的当前分支合并。

### 总结
按照这些步骤，你应该能够诊断为什么VS Code中会出现“没有暂存的更改来提交”的问题，并进行相应的处理。记住，有效的使用Git和VS Code的**源代码管理**面板能帮助你更好地跟踪和提交项目的更改。


修改代码

如何同步

终端输入：

git status

git add .

git commit -m "提交信息"

git pull

代码签名

sync changes

git push


在Git中，"sync changes"通常意味着将本地的更改与远程仓库同步。这可以通过以下步骤实现：

将本地的更改暂存：

git add .

提交这些更改到本地仓库：

git commit -m "Your commit message"

拉取远程仓库的最新更改，以确保你的本地分支是最新的，并且没有冲突：

git pull origin your-branch-name

将你的更改推送到远程仓库：

git push origin your-branch-name

如果在git pull时遇到冲突，你需要手动解决这些冲突，然后再提交更改。

这是一个简单的同步流程。如果你需要处理特定的同步需求（例如，同步特定的文件或文件夹），你可能需要调整这些命令以适应你的具体需求。

将数组 [1, 2, 3, 4, 5] 转换为 数据表


``` sql
SELECT
    exploded_item
FROM (
    SELECT EXPLODE(array(1, 2, 3, 4, 5)) AS exploded_item
) exploded_table
;
```





``` sql
set hive.strict.checks.cartesian.product = false;
set hive.mapred.mode = nostrict;
select
*,
array_contains (a.mall_id_list, b.mall_id)
from
(
select array(1, 2, 3, 4, 5, 8, 9, 10) as mall_id_list union all
select array(4, 5, 6, 7, 9) union all
select array(56)
) a
cross join (
select 9 as mall_id union all
select 2
) b;

```



In [ ]:
from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import pairwise_distances_argmin
from sklearn.metrics.pairwise import pairwise_distances
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

# 假设df是你的DataFrame，'id'是你希望保留的列名
df = pd.DataFrame({
    'id': [1, 2, 3, 4, 5],
    'feature1': [10, 20, 10, 40, 50],
    'feature2': [15, 25, 15, 45, 55],
    # 更多列
})

# 定义权重, make sure the number of weights matches the number of features
feature_weights = [10, 1]  # Now we have weights for feature1 and feature2

# 指定要用于聚类的特征列（不包括'id'列）
features = df.drop('id', axis=1)

# 标准化数据并应用权重
scaler = MinMaxScaler()
features_scaled = scaler.fit_transform(features)
features_scaled_weighted = features_scaled * feature_weights # Apply weights to the scaled features


# 指定聚类的数量
num_clusters = 2

# 创建KMeans模型
kmeans = KMeans(n_clusters=num_clusters, random_state=0)

# 对特征列进行聚类
df['cluster'] = kmeans.fit_predict(features_scaled_weighted) # use weighted features for clustering

# 结果DataFrame现在包括了'id'列和基于指定特征的聚类结果'cluster'列
print(df)

   id  feature1  feature2  cluster
0   1        10        15        0
1   2        20        25        0
2   3        10        15        0
3   4        40        45        1
4   5        50        55        1
